name: Publish package

on:
  push:
    # publish on version tags like v1.2.3
    tags:
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@fsarch'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --registry https://npm.pkg.github.com/


